name: Auto message for Issues
on: [issues]
jobs:
  build:
    name: Hello new contributor
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.SECRET_WRITE }}
          issue-message: "Hey, thank you for opening your first Issue ! 🙂 We will get to this as soon as we can!"
          pr-message: "Hey, thank you for opening your Pull Request ! 🙂 We will get to this as soon as we can!"
